# Data Extraction

### Import

In [1]:
import pandas as pd
from collections import OrderedDict

### Bloomberg path

Run only one time to extract the data. 
This extraction is for 11 variables on a period of 20 years with a daily frequency. The data is extracted with bql on the bloomberg bquant plateform.

import bql

bq = bql.Service()

#MSCI
request_MSCI = """
let(  
    #price = px_last(DATES=range(-20y, 0d, frq=d),fill=PREV);
    )

get(
    #price
    )
for(
    ['M1WO Index']
    )

with(Fill=NA,showids=t, showheaders=f, showallcols=f, mode=cached)

"""

response_MSCI = bq.execute(request_MSCI)
data_MSCI=bql.combined_df(response_MSCI)
df_MSCI = data_MSCI.rename(columns={'#price': 'MSCI'})
df_MSCI.index = df_MSCI['DATE']
df_MSCI = df_MSCI.drop(['DATE','CURRENCY'],axis=1)

#Low-vol
request_vol = """
let(  
    #price = px_last(DATES=range(-20y, 0d, frq=d),fill=PREV);
    )

get(
    #price
    )
for(
    ['M1WOMVOL Index']
    )

with(Fill=NA,showids=t, showheaders=f, showallcols=f, mode=cached)

"""

response_vol = bq.execute(request_vol)
data_vol=bql.combined_df(response_vol)
df_vol = data_vol.rename(columns={'#price': 'LOW_VOL'})
df_vol.index = df_vol['DATE']
df_vol = df_vol.drop(['DATE','CURRENCY'],axis=1)

#Momentum
request_mom = """
let(  
    #price = px_last(DATES=range(-20y, 0d, frq=d),fill=PREV);
    )

get(
    #price
    )
for(
    ['M1WOMOM Index']
    )

with(Fill=NA,showids=t, showheaders=f, showallcols=f, mode=cached)

"""

response_mom = bq.execute(request_mom)
data_mom=bql.combined_df(response_mom)
df_mom = data_mom.rename(columns={'#price': 'MOM'})
df_mom.index = df_mom['DATE']
df_mom = df_mom.drop(['DATE','CURRENCY'],axis=1)

#VIX
request_VIX = """
let(  
    #price = px_last(DATES=range(-20y, 0d, frq=d),fill=PREV);
    )

get(
    #price
    )
for(
    ['VIX Index']
    )

with(Fill=NA,showids=t, showheaders=f, showallcols=f, mode=cached)

"""

response_VIX = bq.execute(request_VIX)
data_VIX=bql.combined_df(response_VIX)
df_VIX = data_VIX.rename(columns={'#price': 'VIX'})
df_VIX.index = df_VIX['DATE']
df_VIX = df_VIX.drop(['DATE','CURRENCY'],axis=1)

#Credit spread
request_CS = """
let(  
    #price = px_last(DATES=range(-20y, 0d, frq=d),fill=PREV);
    )

get(
    #price
    )
for(
    ['BICLB10Y Index']
    )

with(Fill=NA,showids=t, showheaders=f, showallcols=f, mode=cached)

"""

response_CS = bq.execute(request_CS)
data_CS=bql.combined_df(response_CS)
df_CS = data_CS.rename(columns={'#price': 'CS'})
df_CS.index = df_CS['DATE']
df_CS = df_CS.drop(['DATE','CURRENCY'],axis=1)

#GDP growh rate (yearly)
request_GDP = """
let(  
    #price = px_last(DATES=range(-20y, 0d, frq=d),fill=PREV);
    )

get(
    #price
    )
for(
    ['GDPGAWLD Index']
    )

with(Fill=NA,showids=t, showheaders=f, showallcols=f, mode=cached)

"""

response_GDP = bq.execute(request_GDP)
data_GDP=bql.combined_df(response_GDP)
df_GDP = data_GDP.rename(columns={'#price': 'GDP'})
df_GDP.index = df_GDP['DATE']
df_GDP = df_GDP.drop(['DATE','CURRENCY'],axis=1)

#Interest Rate
request_IR = """
let(  
    #price = px_last(DATES=range(-20y, 0d, frq=d),fill=PREV);
    )

get(
    #price
    )
for(
    ['USGG10YR Index']
    )

with(Fill=NA,showids=t, showheaders=f, showallcols=f, mode=cached)

"""

response_IR = bq.execute(request_IR)
data_IR=bql.combined_df(response_IR)
df_IR = data_IR.rename(columns={'#price': 'IR'})
df_IR.index = df_IR['DATE']
df_IR = df_IR.drop(['DATE','CURRENCY'],axis=1)

#CPI (Monthly)
request_CPI = """
let(  
    #price = px_last(DATES=range(-20y, 0d, frq=d),fill=PREV);
    )

get(
    #price
    )
for(
    ['CPI YOY Index']
    )

with(Fill=NA,showids=t, showheaders=f, showallcols=f, mode=cached)

"""

response_CPI = bq.execute(request_CPI)
data_CPI=bql.combined_df(response_CPI)
df_CPI = data_CPI.rename(columns={'#price': 'CPI'})
df_CPI.index = df_CPI['DATE']
df_CPI = df_CPI.drop(['DATE','CURRENCY'],axis=1)

#Liquidity
request_liq = """
let(  
    #price = px_last(DATES=range(-20y, 0d, frq=d),fill=PREV);
    )

get(
    #price
    )
for(
    ['GFSIRLIQ Index']
    )

with(Fill=NA,showids=t, showheaders=f, showallcols=f, mode=cached)

"""

response_liq = bq.execute(request_liq)
data_liq=bql.combined_df(response_liq)
df_liq = data_liq.rename(columns={'#price': 'Liquidity'})
df_liq.index = df_liq['DATE']
df_liq = df_liq.drop(['DATE','CURRENCY'],axis=1)

#PutCall
request_PC = """
let(  
    #price = px_last(DATES=range(-20y, 0d, frq=d),fill=PREV);
    )

get(
    #price
    )
for(
    ['PCUSEQTR Index']
    )

with(Fill=NA,showids=t, showheaders=f, showallcols=f, mode=cached)

"""

response_PC = bq.execute(request_PC)
data_PC=bql.combined_df(response_PC)
df_PC = data_PC.rename(columns={'#price': 'PUT/CALL'})
df_PC.index = df_PC['DATE']
df_PC = df_PC.drop(['DATE','CURRENCY'],axis=1)

#Crude Oil
request_CO = """
let(  
    #price = px_last(DATES=range(-20y, 0d, frq=d),fill=PREV);
    )

get(
    #price
    )
for(
    ['CL1 Comdty']
    )

with(Fill=NA,showids=t, showheaders=f, showallcols=f, mode=cached)

"""

response_CO = bq.execute(request_CO)
data_CO=bql.combined_df(response_CO)
df_CO = data_CO.rename(columns={'#price': 'Crude Oil'})
df_CO.index = df_CO['DATE']
df_CO = df_CO.drop(['DATE','CURRENCY'],axis=1)

#Interest rate spread 2Y
request_IR2YSP = """
let(  
    #price = px_last(DATES=range(-20y, 0d, frq=d),fill=PREV);
    )

get(
    #price
    )
for(
    ['USOSFR2 BGN Curncy']
    )

with(Fill=NA,showids=t, showheaders=f, showallcols=f, mode=cached)

"""

response_IR2YSP = bq.execute(request_IR2YSP)
data_IR2YSP=bql.combined_df(response_IR2YSP)
df_IR2YSP = data_IR2YSP.rename(columns={'#price': 'IR2YSP'})
df_IR2YSP.index = df_IR2YSP['DATE']
df_IR2YSP = df_IR2YSP.drop(['DATE','CURRENCY'],axis=1)

### Create the dataFrame

data_concat = pd.concat([df_MSCI,df_vol,df_mom,df_VIX,df_CS,df_GDP,df_IR,df_CPI,df_liq,df_PC,df_CO,df_IR2YSP ],axis=1)
data_cleaned = data_concat.dropna(how='all')
data_cleaned.head()

Save data

data_cleaned.to_csv('data.csv',index=True)

### Import data Test

In [2]:
# Import check
data = pd.read_csv('data/data.csv')
data = data.drop('IR2YSP', axis =1)
data.head(10000)

,DATE,MSCI,LOW_VOL,MOM,VIX,CS,GDP,IR,CPI,Liquidity,PUT/CALL,Crude Oil
0,2004-11-22,2422.10,1251.67,610.76,12.97,196.16000,NaN,4.178435,3.18919,-0.11,0.53,48.640000
1,2004-11-23,2425.34,1254.95,611.55,12.67,196.77000,NaN,4.182256,3.18919,-0.10,0.66,48.940000
2,2004-11-24,2437.26,1260.16,616.27,12.72,195.24000,NaN,4.197622,3.18919,-0.11,0.49,49.440000
3,2004-11-25,2449.94,1265.83,619.00,12.72,195.24000,NaN,4.193688,3.18919,-0.10,0.49,49.440000
4,2004-11-26,2449.84,1267.34,619.99,12.78,195.41000,NaN,4.245909,3.18919,-0.11,0.58,49.440000
...,...,...,...,...,...,...,...,...,...,...,...,...
7301,2024-11-18,11766.87,5190.08,4684.71,15.58,143.60004,2.719333,4.413842,2.59791,-0.08,0.51,69.160000
7302,2024-11-19,11816.24,5185.92,4716.10,16.35,143.79001,2.719333,4.396175,2.59791,-0.03,0.62,69.390000
7303,2024-11-20,11797.02,5198.70,4716.46,17.16,140.59000,2.719333,4.409950,2.59791,-0.05,0.58,68.870000
7304,2024-11-21,11863.74,5245.22,4740.40,16.87,143.39999,2.719333,4.421781,2.59791,-0.05,0.53,70.100000
7305,2024-11-22,11863.74,5245.22,4740.40,16.22,143.39999,2.719333,4.417911,2.59791,-0.05,0.53,70.720001